examenParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestionTienda/',include('gestionTienda.urls')),
]

gestionTienda/urls.py
from django.urls import path
from .import views

app_name = 'gestionTienda'

urlpatterns = [
    path('',views.index,name='index'),
    path('productos',views.productos,name='productos'),
    path('tiendas',views.tiendas,name='tiendas'),

    path('agregarTienda',views.agregarTienda,name='agregarTienda'),
    path('agregarProducto',views.agregarProducto,name='agregarProducto'),

    path('editarProducto/<str:idProducto>',views.editarProducto,name='editarProducto'),
    path('saveProducto',views.saveProducto,name='saveProducto'),

    path('eliminarProducto/<str:idProducto>',views.eliminarProducto,name='eliminarProducto'),
    path('eliminarTienda/<str:idTienda>',views.eliminarTienda,name='eliminarTienda'),

    path('detalleTienda/<str:idTienda>',views.detalleTienda,name='detalleTienda')
]

gestionTienda/models.py
from django.db import models

# Create your models here.
class tienda(models.Model):
    direccion = models.CharField(max_length=50) 
    provincia = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    fechaCreacion = models.DateField(null=True, blank=True)
    telefonoContacto = models.CharField(max_length=9)

class producto(models.Model):
    descripcion = models.CharField(max_length=100)
    codigo = models.CharField(max_length=4)
    precioVenta = models.DecimalField(max_digits=5,decimal_places=2)
    cantidad = models.IntegerField(4)
    tiendaRelacionada = models.ForeignKey(tienda,blank=True,null=True,on_delete=models.SET_NULL)

gestionTienda/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import tienda
from .models import producto

listaTiendas = []
listaProductos = []

# Create your views here.

def index(request):
    return HttpResponse("Bienvenidos a django")

def productos(request):
     return render(request,'productos.html',{
         'listaProductos':producto.objects.all()
         })


def tiendas(request):
    return render(request,'tiendas.html',{
         'listaTiendas':tienda.objects.all()
         })

def agregarTienda(request):
    print(request.POST)

    if request.method == 'POST':
        direccion = request.POST.get('direccion')
        provincia = request.POST.get('provincia')
        region = request.POST.get('region')
        fechaCreacion = request.POST.get('fechaCreacion')
        telefono = request.POST.get('telefono')
        print(direccion)
        print(provincia)

        tienda.objects.create(
            direccion = direccion,
            provincia = provincia,
            region = region,
            fechaCreacion = fechaCreacion,
            telefonoContacto = telefono
        )

        return HttpResponseRedirect(reverse('gestionTienda:tiendas'))
    return render(request,'agregarTienda.html')

def agregarProducto(request):
     if request.method == 'POST':
        descripcion = request.POST.get('descripcion')
        codigo = request.POST.get('codigo')
        precioVenta = request.POST.get('precioVenta')
        cantidad = request.POST.get('cantidad')
       
        producto.objects.create(
            descripcion = descripcion,
            codigo = codigo,
            precioVenta = precioVenta,
            cantidad = cantidad,
        )

        return HttpResponseRedirect(reverse('gestionTienda:productos'))
     return render(request,'agregarProducto.html')

def editarProducto(request,idProducto):
    objProducto = producto.objects.get(id=idProducto)
    return render(request,'editarProducto.html',{
        'objProducto':objProducto, 'listaTiendas':tienda.objects.all()
    })

def saveProducto(request):
    
     codigo = request.POST['id']

     print(f'valor {{% codigo %}}')
     tienda = request.POST['tienda']
     Producto = producto.objects.get(id=codigo)

     Producto.tiendaRelacionada = tienda
     Producto.save()
     return HttpResponseRedirect(reverse('gestionTienda:productos'))


def eliminarProducto(request,idProducto):
    Producto = producto.objects.get(id=idProducto)
    Producto.delete()

    return HttpResponseRedirect(reverse('gestionTienda:productos'))

def eliminarTienda(request,idTienda):
    Tienda = tienda.objects.get(id=idTienda)
    Tienda.delete()

    return HttpResponseRedirect(reverse('gestionTienda:tiendas'))

def detalleTienda(request,idTienda):
    objProducto = producto.objects.get(id=idTienda)
    return render(request,'detalleTienda.html',{
        'objProducto':objProducto
    })





# Ruta: 127.1.1.0:800/gestionTienda

gestionTienda/templates/detalleTienda.html
<!DOCTYPE html>
<html>
    <head>
        <title>Detalle Tienda</title>
    </head>
    <body>
       <a href="{% url 'gestionTienda:tiendas' %}">Regresar</a>
       <h3>Producto: {{ objProducto.descripcion }}</h3>
    </body>
</html>

gestionTienda/templates/editarProducto.html
<!DOCTYPE html>
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      
    </head>
    <body>
       
                <div class="container">
                    <form method="post" action="{% url 'gestionTienda:saveProducto'}">
                      {% csrf_token %}
                        <div class="modal-header">
                            <h5 class="modal-title">Asignar Tienda</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <div class="row mb-3 mt-3">
                            <div>
                              <input type="text" class="form-control"  value="{{objProducto.id}}" name="id" hidden="true" readonly>
                            </div>
                            <div class="col-6">
                              <label>Descripcion</label>
                              <input type="text" class="form-control"  value="{{objProducto.descripcion}}" name="descripcion" readonly>
                            </div>
                            <div class="col-6">
                              <label>Codigo</label> 
                              <input type="text"  class="form-control"  value="{{objProducto.codigo}}" name="codigo" readonly>
                            </div>
                          </div>
                            <div class="row mb-3 mt-3">
                                <div class="col-6">
                                <label>precio de Venta</label>
                                <input type="text" class="form-control" value="{{objProducto.precioVenta}}" name="precioVenta" readonly>
                                </div>
                                <div class="col-6">
                                <label>Cantidad</label>
                                <input type="number" class="form-control" value="{{objProducto.cantidad}}" name="cantidad" readonly>
                              </div>
                            </div>

                            <div class="row mb-3 mt-3">
                                <div class="col-6">
                                <label>Tienda</label>
                            <select class="form-select" name="tienda">
                                <option selected="">Seleccionar</option>
                                {% for tiendas in listaTiendas %} 
                                <option value="{{tiendas.id}}">{{tiendas.direccion}}</option>
                                {% endfor %}
                            </select>
                              </div>
                            </div>
                          

                            
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-primary">Registrar</button>
                        </div>
                    </form>
                </div>
           
    </body>
</html>




<div class="modal fade" id="editarProducto" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="#">
              {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Asignar Tienda</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="row mb-3 mt-3">
                    <div class="col-6">
                      <label>Descripcion</label>
                      <input type="text" class="form-control"  value="{{objProducto.descripcion}}" name="descripcion" readonly>
                    </div>
                    <div class="col-6">
                      <label>Codigo</label> 
                      <input type="text"  class="form-control"  value="{{objProducto.codigo}}" name="codigo" readonly>
                    </div>
                  </div>
                    <div class="row mb-3 mt-3">
                        <div class="col-6">
                        <label>precio de Venta</label>
                        <input type="text" class="form-control" value="{{objProducto.precioVenta}}" name="precioVenta" readonly>
                        </div>
                        <div class="col-6">
                        <label>Cantidad</label>
                        <input type="number" class="form-control" value="{{objProducto.cantidad}}" name="cantidad" readonly>
                      </div>
                    </div>
                    <div class="row mb-3 mt-3">
                        <div class="col-6">
                        <label>Tienda</label>
                        <input type="text" class="form-select" value="{{objProducto.cantidad}}" name="cantidad" readonly>
                      </div>
                    </div>
                  
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

gestionTienda/templates/productos.html
<!DOCTYPE html>
<html>
    <head>
       <title></title>

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="row ">
                    <h2 style="text-align: center; padding-bottom: 2pc;">GESTIÓN DE TIENDAS</h2> 
                </div>
                <div class="row justify-content-center">
                    <div class="col-6" style="text-align: end;">
                        <a class="btn btn-success"  href="{% url 'gestionTienda:tiendas' %}"><i class="fa-solid fa-user-plus"></i> Tiendas</a>
                    </div>
                <div class="col-6">
                    <a class="btn btn-success"  href="{% url 'gestionTienda:productos' %}"><i class="fa-solid fa-user-plus"></i> Productos</a>

                </div>
                </div>
            </div>
        </div>    
        <div class="mt-5 container">
          <div class="row justify-content-center">
              <div class="row">
                <h3 style="text-align: center; padding-bottom: 2pc;">Listado de Productos</h3>
              </div>
              <div class="col-11">
                  <table class="table table-bordered">
                      <thead class="table-dark">
                          <th>Descripcion</th>
                          <th>Codigo</th>
                          <th>Precio de Venta</th>
                          <th>Cantidad</th>
                          <th>Editar</th>
                          <th>Eliminar</th>
                      </thead>
                      {% for producto in listaProductos %}
                      <tbody>
                          <tr>
                              <td>{{ producto.descripcion }}</td>
                              <td>{{ producto.codigo }}</td>
                              <td>{{ producto.precioVenta }}</td>
                              <td>{{ producto.cantidad}}</td>
                              <td class="text-center"><a class="btn btn-warning btnTable" href="{% url 'gestionTienda:editarProducto' producto.id %}"><i class="fa-solid fa-edit "></i></a></td>
                              <td class="text-center"><a class="btn btn-danger btnTable" href="{% url 'gestionTienda:eliminarProducto' producto.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
                          </tr>
                      </tbody>
                      {% endfor%}
                  </table>
                  <div style="text-align: end;">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoProducto"><i class="fa-solid fa-user-plus"></i> Agregar Producto</button>
                  </div>
              </div>
          </div>
      </div>
    </body>
</html>

<!--Nuevo usuario-->
<div class="modal fade" id="nuevoProducto" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'gestionTienda:agregarProducto'%}">
              {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Agregar Producto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="row mb-3 mt-3">
                    <div class="col-6">
                      <label>Descripcion</label>
                      <input type="text" class="form-control"  name="descripcion">
                    </div>
                    <div class="col-6">
                      <label>Codigo</label>
                      <input type="text"  class="form-control" name="codigo">
                    </div>
                  </div>
                    <div class="row mb-3 mt-3">
                        <div class="col-6">
                        <label>precio de Venta</label>
                        <input type="text" class="form-control" name="precioVenta">
                        </div>
                        <div class="col-6">
                        <label>Cantidad</label>
                        <input type="number" class="form-control" name="cantidad">
                      </div>
                    </div>
                  
                  
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

gestionTienda/templates/tiendas.html
<!DOCTYPE html>
<html>
    <head>
       <title></title>

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
      <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="row ">
                <h2 style="text-align: center; padding-bottom: 2pc;">GESTIÓN DE TIENDAS</h2> 
            </div>
            <div class="row justify-content-center">
                <div class="col-6" style="text-align: end;">
                    <a class="btn btn-success"  href="{% url 'gestionTienda:tiendas' %}"><i class="fa-solid fa-user-plus"></i> Tiendas</a>
                </div>
            <div class="col-6">
                <a class="btn btn-success"  href="{% url 'gestionTienda:productos' %}"><i class="fa-solid fa-user-plus"></i> Productos</a>

            </div>
            </div>
        </div>
    </div> 
        <div class="mt-5 container">
          <div class="row justify-content-center">
              <div class="row">
                <h3 style="text-align: center; padding-bottom: 2pc;">Listado de Tiendas</h3>
              </div>
              <div class="col-11">
                  <table class="table table-bordered">
                      <thead class="table-dark">
                          <th>Direccion</th>
                          <th>Provincia</th>
                          <th>Fecha de Creacion</th>
                          <th>Telefono</th>
                          <th>Ver</th>
                          <th>Eliminar</th>
                      </thead>
                      {% for tiendas in listaTiendas %}
                      <tbody>
                          <tr>
                              <td>{{ tiendas.direccion }}</td>
                              <td>{{ tiendas.provincia }}</td>
                              <td>{{ tiendas.fechaCreacion }}</td>
                              <td>{{ tiendas.telefonoContacto }}</td>
                              <td class="text-center"><a class="btn btn-info btnTable" href="{% url 'gestionTienda:detalleTienda' tiendas.id %}"><i class="fa-solid fa-eye btnicon"></i></a></td>
                              <td class="text-center"><a class="btn btn-danger btnTable" href="{% url 'gestionTienda:eliminarTienda' tiendas.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
                          </tr>
                      </tbody>
                      {% endfor%}
                  </table>
                  <div style="text-align: end;">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoTienda"><i class="fa-solid fa-user-plus"></i> Agregar Tienda</button>
                  </div>
              </div>
          </div>
      </div>
    </body>
</html>

<!--Nuevo usuario-->
<div class="modal fade" id="nuevoTienda" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'gestionTienda:agregarTienda' %}">
              {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Agregar Tienda</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="row mb-3 mt-3">
                    <div class="col-6">
                      <label>Direccion</label>
                      <input type="text" class="form-control"  name="direccion">
                    </div>
                    <div class="col-6">
                      <label>Provincia</label>
                      <input type="text"  class="form-control" name="provincia">
                    </div>
                  </div>
                    <div class="row mb-3 mt-3">
                      <div class="col-6">
                        <label>Region</label>
                        <input type="text" class="form-control" name="region">
                      </div>
                      <div class="col-6">
                        <label>Fecha de Creacion</label>
                        <input type="date"  class="form-control" name="fechaCreacion">
                      </div>
                    </div>
                    <div class="row mb-3 mt-3">
                      <div class="col-6">
                        <label>Telefono</label>
                        <input type="text" class="form-control" name="telefono">
                      </div>
                    </div>
                  
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>